include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_empty_else
    - avoid_null_checks_in_equality_operators
    - avoid_relative_lib_imports
    - avoid_returning_null_for_void
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - prefer_collection_literals
    - prefer_const_constructors
    - prefer_contains
    - prefer_final_in_for_each
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
