name: fotodesk
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  auto_route: ^5.0.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  dio: ^5.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  easy_localization: ^3.0.3
  shared_preferences: ^2.2.1
  flutter_screenutil: ^5.9.0
  elegant_notification: ^1.11.1
  intl: ^0.18.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  file_picker: ^5.5.0
  fl_chart: ^0.63.0
  flutter_secure_storage: ^9.0.0
  timezone: ^0.9.2
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.1.0+1
  json_serializable: ^6.7.1
  easy_localization_loader: ^1.0.1+1
  auto_route_generator: ^5.0.3

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/localization/en.json
    - assets/localization/de.json
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
